import "./global.scss"
import Header from "./_components/header"
import Footer from "./_components/footer"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <head>
      </head>
      <body className="min-h-full relative overflow-x-hidden">
        <Header></Header>
        {children}
        
        <Footer></Footer>
      </body>
    </html>
  )
}
